COMPOSE_PROJECT_NAME=ngb-pm

# Build
BUILD_CONFIGURATION=Release

# ASP.NET Core certificates
ASPNET_CERT_PASS=111111
ASPNET_CERT_PATH=/https/servercert.pfx

# Property Management service host ports
PM_API_HTTP_PORT=5051
PM_API_HTTPS_PORT=7071
PM_BACKGROUNDJOBS_HTTP_PORT=5054
PM_BACKGROUNDJOBS_HTTPS_PORT=7074
PM_WATCHDOG_HTTP_PORT=5055
PM_WATCHDOG_HTTPS_PORT=7075
PM_WEB_HTTP_PORT=5173

# Seq
SEQ_IMAGE_TAG=2025.2
SEQ_HTTP_HOST_PORT=5342
SEQ_URL=http://ngb.pm.seq
SEQ_API_KEY=1f92ff68-ff3f-44bd-90a7-06584a530e6b
SEQ_DEFAULT_ADMIN_NAME=user@example.com
SEQ_DEFAULT_ADMIN_PASSWORD=Password(55)60-stronG-start

# PostgreSQL
POSTGRES_IMAGE_TAG=18.3-alpine
POSTGRES_HOST_PORT=5433
POSTGRES_ADMIN_USER=ngb_platform_admin
POSTGRES_ADMIN_PASSWORD=Password(55)60-stronG-db
PM_DB_NAME=ngb_pm
PM_DB_USER=ngb_pm_app
PM_DB_PASSWORD=Password(55)60-stronG-pm
KEYCLOAK_DB_NAME=ngb_pm_keycloak
KEYCLOAK_DB_USER=ngb_pm_keycloak_app
KEYCLOAK_DB_PASSWORD=Password(55)60-stronG-pm-kc

# pgAdmin
PGADMIN_IMAGE_TAG=9.14
PGADMIN_HTTP_HOST_PORT=4882
PGADMIN_DEFAULT_EMAIL=user@example.com
PGADMIN_DEFAULT_PASSWORD=Password(55)60-stronG

# Property Management demo bootstrap
PM_DEMO_SEED_ENABLED=true
PM_DEMO_DATASET=demo
PM_DEMO_SEED=20260412
PM_DEMO_SEED_FROM=2024-01-01
PM_DEMO_SEED_TO=
PM_DEMO_BUILDINGS=
PM_DEMO_UNITS_MIN=
PM_DEMO_UNITS_MAX=
PM_DEMO_TENANTS=
PM_DEMO_VENDORS=
PM_DEMO_OCCUPANCY_RATE=

# Keycloak
KEYCLOAK_IMAGE_TAG=26.5.6
KEYCLOAK_HTTP_HOST_PORT=7012
KEYCLOAK_PUBLIC_HOST=pm-keycloak.localhost
KEYCLOAK_INTERNAL_URL=http://ngb.pm.keycloak:8080
KEYCLOAK_PUBLIC_URL=http://pm-keycloak.localhost:7012
KEYCLOAK_LOG_LEVEL=info
KEYCLOAK_MASTER_ADMIN_USERNAME=admin
KEYCLOAK_MASTER_ADMIN_PASSWORD=Password(55)60-stronG
KEYCLOAK_REALM=ngb-demo
KEYCLOAK_REALM_DISPLAY_NAME=NGB Demo
KEYCLOAK_REALM_DISPLAY_NAME_HTML=<strong>NGB Demo</strong>
KEYCLOAK_THEME_NAME=ngb-auth
KEYCLOAK_SSL_REQUIRED=external
KEYCLOAK_ACCESS_TOKEN_LIFESPAN_SECONDS=3600
KEYCLOAK_LOGIN_WITH_EMAIL_ALLOWED=true
KEYCLOAK_REGISTRATION_ALLOWED=false
KEYCLOAK_REGISTRATION_EMAIL_AS_USERNAME=true
KEYCLOAK_RESET_PASSWORD_ALLOWED=true
KEYCLOAK_VERIFY_EMAIL=false
KEYCLOAK_REMEMBER_ME=true
KEYCLOAK_BRUTE_FORCE_PROTECTED=true
KEYCLOAK_PM_API_CLIENT_ID=ngb-pm-api
KEYCLOAK_PM_WEB_CLIENT_ID=ngb-pm-web-client
KEYCLOAK_PM_BACKGROUND_JOBS_CLIENT_ID=ngb-pm-background-jobs
KEYCLOAK_PM_WATCHDOG_CLIENT_ID=ngb-pm-watchdog
KEYCLOAK_TESTER_CLIENT_ID=ngb-tester
KEYCLOAK_TESTER_CLIENT_SECRET=ngb-pm-tester-secret-2026
KEYCLOAK_DEMO_ADMIN_USERNAME=alex.carter@demo.ngbplatform.com
KEYCLOAK_DEMO_ADMIN_FIRST_NAME=Alex
KEYCLOAK_DEMO_ADMIN_LAST_NAME=Carter
KEYCLOAK_DEMO_ADMIN_EMAIL=alex.carter@demo.ngbplatform.com
KEYCLOAK_DEMO_ADMIN_PASSWORD=DemoAdmin!2026
