<Project>
    <PropertyGroup>
        <NgbPlatformVersion>3.1.0</NgbPlatformVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
    </PropertyGroup>
</Project>
