<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <IsPublishable>false</IsPublishable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NGB.CRM\NGB.CRM.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="NGB.Platform.Application.Abstractions" Version="$(NgbPlatformPackageVersion)" />
        <PackageReference Include="NGB.Platform.Contracts" Version="$(NgbPlatformPackageVersion)" />
        <PackageReference Include="NGB.Platform.Definitions" Version="$(NgbPlatformPackageVersion)" />
        <PackageReference Include="NGB.Platform.Metadata" Version="$(NgbPlatformPackageVersion)" />
        <PackageReference Include="NGB.Platform.ReferenceRegisters" Version="$(NgbPlatformPackageVersion)" />
        <PackageReference Include="NGB.Platform.Runtime" Version="$(NgbPlatformPackageVersion)" />
        <PackageReference Include="NGB.Platform.Tools" Version="$(NgbPlatformPackageVersion)" />
    </ItemGroup>

</Project>
