using Dapper;
using FluentAssertions;
using Microsoft.Extensions.Logging.Abstractions;
using NGB.PostgreSql.Schema;
using NGB.PostgreSql.UnitOfWork;
using Npgsql;
using Xunit;

namespace NGB.Runtime.IntegrationTests.Infrastructure;

[Collection(PostgresCollection.Name)]
public sealed class PlatformSchema_DetectsMismatchTests(PostgresTestFixture fixture)
    : IntegrationTestBase(fixture)
{
    [Fact]
    public async Task DbSchemaInspectorSnapshot_DetectsMissingCoreColumn()
    {
        // IMPORTANT:
        // This test deliberately breaks a core table. If we do it in the shared integration DB,
        // other tests will start failing because our platform migrations are "CREATE IF NOT EXISTS"
        // and will NOT restore dropped columns.
        // So we create a dedicated temporary database for this test and drop it afterwards.

        string dbName = $"ngb_mismatch_{Guid.CreateVersion7():N}";
        string tempConnStr = BuildDatabaseConnectionString(Fixture.ConnectionString, dbName);

        await CreateDatabaseAsync(Fixture.ConnectionString, dbName);

        try
        {
            await MigrationSet.ApplyPlatformMigrationsAsync(tempConnStr);

            // Fault-injection: deliberately break a core table.
            await DropAccountsNameColumnAsync(tempConnStr);

            // Read schema snapshot (no DI required; we want full control over the connection).
            await using var uow = new PostgresUnitOfWork(tempConnStr, NullLogger<PostgresUnitOfWork>.Instance);
            var inspector = new PostgresSchemaInspector(uow);

            var snapshot = await inspector.GetSnapshotAsync(CancellationToken.None);

            snapshot.Tables.Should().Contain("accounting_accounts");
            snapshot.ColumnsByTable.Should().ContainKey("accounting_accounts");

            var actualColumns = snapshot.ColumnsByTable["accounting_accounts"].Select(c => c.ColumnName).ToHashSet();

            // Minimal expected column set from platform migrations (see AccountingAccountsMigration).
            var expectedColumns = new HashSet<string>
            {
                "account_id",
                "code",
                "name",
                "account_type",
                "statement_section",
                "is_contra",                "negative_balance_policy",
                "is_active",
                "is_deleted",
                "created_at_utc",
                "updated_at_utc"
            };

            var missing = expectedColumns.Except(actualColumns).ToArray();

            // The test intentionally broke the schema, so we must observe the mismatch.
            missing.Should().Contain("name");
        }
        finally
        {
            await DropDatabaseAsync(Fixture.ConnectionString, dbName);
        }
    }

    private static async Task DropAccountsNameColumnAsync(string connectionString)
    {
        await using var conn = new NpgsqlConnection(connectionString);
        await conn.OpenAsync();

        // CASCADE is required because there is a CHECK constraint referencing the column.
        const string sql = "ALTER TABLE accounting_accounts DROP COLUMN name CASCADE;";

        await using var cmd = new NpgsqlCommand(sql, conn);
        await cmd.ExecuteNonQueryAsync();
    }

    private static string BuildDatabaseConnectionString(string baseConnectionString, string database)
    {
        var b = new NpgsqlConnectionStringBuilder(baseConnectionString)
        {
            Database = database
        };
        return b.ConnectionString;
    }

    private static async Task CreateDatabaseAsync(string baseConnectionString, string database)
    {
        var admin = new NpgsqlConnectionStringBuilder(baseConnectionString)
        {
            Database = "postgres"
        };

        await using var conn = new NpgsqlConnection(admin.ConnectionString);
        await conn.OpenAsync();

        // Quote to keep the name safe; database name is generated by us.
        string sql = $"CREATE DATABASE \"{database}\";";
        await conn.ExecuteAsync(sql);
    }

    private static async Task DropDatabaseAsync(string baseConnectionString, string database)
    {
        var admin = new NpgsqlConnectionStringBuilder(baseConnectionString)
        {
            Database = "postgres"
        };

        await using var conn = new NpgsqlConnection(admin.ConnectionString);
        await conn.OpenAsync();

        // FORCE is available in PostgreSQL 13+ and is useful to avoid "being accessed" errors.
        string sql = $"DROP DATABASE IF EXISTS \"{database}\" WITH (FORCE);";
        await conn.ExecuteAsync(sql);
    }
}
