<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPublishable>false</IsPublishable>
        <PackageId>NGB.Platform.Tools</PackageId>
        <Description>Foundational utilities, exception types, normalization helpers, and low-level extensions for NGB Platform.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FastEnum" Version="2.0.6"/>
    </ItemGroup>

</Project>
