export const NGB_ICON_NAMES = [
  'arrow-left',
  'arrow-right',
  'plus',
  'minus',
  'trash',
  'trash-restore',
  'check',
  'undo',
  'panel-left',
  'panel-right',
  'grip-vertical',
  'bell',
  'help-circle',
  'settings',
  'cogs',
  'sun',
  'moon',
  'search',
  'filter',
  'composer',
  'play',
  'refresh',
  'download',
  'open-in-new',
  'load-variant',
  'x',
  'save',
  'edit',
  'share',
  'copy',
  'printer',
  'more-vertical',
  'log-out',
  'history',
  'circle-x',
  'home',
  'grid',
  'list',
  'file-text',
  'bar-chart',
  'calculator',
  'book-open',
  'receipt',
  'user',
  'users',
  'building-2',
  'coins',
  'wallet',
  'wrench',
  'clipboard-list',
  'check-square',
  'tag',
  'landmark',
  'calendar-check',
  'scale',
  'git-merge',
  'shield',
  'shield-check',
  'heart-pulse',
  'inspect-check',
  'selected-check',
  'close-month',
  'chevrons-left',
  'chevrons-right',
  'effects-flow',
  'file-apply',
  'document-flow',
] as const

export type NgbIconName = typeof NGB_ICON_NAMES[number]

const iconNameSet = new Set<string>(NGB_ICON_NAMES)

export function isNgbIconName(value: string | null | undefined): value is NgbIconName {
  return typeof value === 'string' && iconNameSet.has(value)
}

export function coerceNgbIconName(value: string | null | undefined, fallback: NgbIconName): NgbIconName {
  return isNgbIconName(value) ? value : fallback
}
