<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NGB.CRM\NGB.CRM.csproj" />
        <ProjectReference Include="..\NGB.CRM.PostgreSql\NGB.CRM.PostgreSql.csproj" />
        <ProjectReference Include="..\NGB.CRM.Runtime\NGB.CRM.Runtime.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="NGB.Platform.BackgroundJobs" Version="$(NgbPlatformPackageVersion)" />
        <PackageReference Include="NGB.Platform.BackgroundJobs.PostgreSql" Version="$(NgbPlatformPackageVersion)" />
        <PackageReference Include="NGB.Platform.PostgreSql" Version="$(NgbPlatformPackageVersion)" />
        <PackageReference Include="NGB.Platform.Runtime" Version="$(NgbPlatformPackageVersion)" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

</Project>
