<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPublishable>true</IsPublishable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NGB.Accounting\NGB.Accounting.csproj"/>
        <ProjectReference Include="..\NGB.Application.Abstractions\NGB.Application.Abstractions.csproj"/>
        <ProjectReference Include="..\NGB.Contracts\NGB.Contracts.csproj"/>
        <ProjectReference Include="..\NGB.Core\NGB.Core.csproj"/>
        <ProjectReference Include="..\NGB.Migrator.Core\NGB.Migrator.Core.csproj"/>
        <ProjectReference Include="..\NGB.Persistence\NGB.Persistence.csproj"/>
        <ProjectReference Include="..\NGB.PostgreSql\NGB.PostgreSql.csproj"/>
        <ProjectReference Include="..\NGB.PropertyManagement\NGB.PropertyManagement.csproj"/>
        <ProjectReference Include="..\NGB.PropertyManagement.PostgreSql\NGB.PropertyManagement.PostgreSql.csproj"/>
        <ProjectReference Include="..\NGB.PropertyManagement.Runtime\NGB.PropertyManagement.Runtime.csproj"/>
        <ProjectReference Include="..\NGB.Runtime\NGB.Runtime.csproj"/>
        <ProjectReference Include="..\NGB.Tools\NGB.Tools.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
    </ItemGroup>

</Project>
