<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPublishable>false</IsPublishable>
        <PackageId>NGB.Platform.Watchdog</PackageId>
        <Description>Reusable health and operability hosting surface for NGB Platform environments.</Description>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0"/>
        <PackageReference Include="AspNetCore.HealthChecks.UI" Version="9.0.0"/>
        <PackageReference Include="AspNetCore.HealthChecks.UI.InMemory.Storage" Version="9.0.0"/>
        <PackageReference Include="KubernetesClient" Version="19.0.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NGB.Api\NGB.Api.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="dashboard.css">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Pack>true</Pack>
            <PackagePath>contentFiles/any/any</PackagePath>
            <PackageCopyToOutput>true</PackageCopyToOutput>
        </None>
    </ItemGroup>

</Project>
