import { jsonHas, operationSucceeded } from '../../../ngb-performance-tests-framework/src/core/checks.ts';
import { randomSuffix } from '../../../ngb-performance-tests-framework/src/core/random.ts';
import type { NgbScenarioContext } from '../../../ngb-performance-tests-framework/src/scenarios/scenarioTypes.ts';
import { PM_CATALOG_TYPES } from '../clients/pmCatalogTypes.ts';
import { PM_DOCUMENT_TYPES } from '../clients/pmDocumentTypes.ts';
import {
  cleanupCreatedDraftsEnabled,
  firstItemId,
  postingEnabled,
  resolveFixtureId,
  resolvePeriodProfile,
  responseDocumentId,
} from './pmFlowSupport.ts';
import { pmPlatformAuditFlow } from './pmPlatformAuditFlow.ts';

export function pmDocumentLifecycleFlow(context: NgbScenarioContext): boolean {
  if (!context.env.enableWrites) {
    readLifecycleSurfaces(context);
    return false;
  }

  const fixture = resolveMaintenanceRequestFixture(context);
  if (!fixture) {
    readLifecycleSurfaces(context);
    return false;
  }

  const period = resolvePeriodProfile('open');
  const suffix = randomSuffix('pm-perf-maintenance');
  const createPayload = maintenanceRequestPayload(
    fixture,
    `Perf maintenance lifecycle ${suffix}`,
    'normal',
    period.asOfUtc,
  );
  const createResponse = context.documents.createDocument(PM_DOCUMENT_TYPES.maintenanceRequest, createPayload);
  operationSucceeded(createResponse, [200, 201]);
  jsonHas(createResponse, 'id');

  const documentId = responseDocumentId(createResponse);
  if (!documentId) {
    return false;
  }

  const updateResponse = context.documents.updateDocument(
    PM_DOCUMENT_TYPES.maintenanceRequest,
    documentId,
    maintenanceRequestPayload(fixture, `Perf maintenance lifecycle updated ${suffix}`, 'high', period.asOfUtc),
  );
  operationSucceeded(updateResponse, [200]);

  operationSucceeded(context.documents.openDocument(PM_DOCUMENT_TYPES.maintenanceRequest, documentId), [200]);
  operationSucceeded(context.documents.getEditorState(PM_DOCUMENT_TYPES.maintenanceRequest, documentId), [200]);
  pmPlatformAuditFlow(context, documentId);

  if (postingEnabled(context)) {
    operationSucceeded(context.documents.postDocument(PM_DOCUMENT_TYPES.maintenanceRequest, documentId), [200]);
    operationSucceeded(context.documents.getDocumentFlow(PM_DOCUMENT_TYPES.maintenanceRequest, documentId, 2, 100), [200]);
    pmPlatformAuditFlow(context, documentId);
    return true;
  }

  if (cleanupCreatedDraftsEnabled()) {
    operationSucceeded(context.documents.deleteDraft(PM_DOCUMENT_TYPES.maintenanceRequest, documentId), [200, 202, 204]);
  }

  return true;
}

function readLifecycleSurfaces(context: NgbScenarioContext): void {
  operationSucceeded(context.documents.getDocumentMetadata(PM_DOCUMENT_TYPES.maintenanceRequest), [200]);
  const page = context.documents.listDocuments(PM_DOCUMENT_TYPES.maintenanceRequest, {
    offset: 0,
    limit: 20,
    filters: { deleted: 'active' },
  });
  operationSucceeded(page, [200]);
  jsonHas(page, 'items');

  const firstId = firstItemId(page);
  if (firstId) {
    operationSucceeded(context.documents.openDocument(PM_DOCUMENT_TYPES.maintenanceRequest, firstId), [200]);
    operationSucceeded(context.documents.getEditorState(PM_DOCUMENT_TYPES.maintenanceRequest, firstId), [200]);
    pmPlatformAuditFlow(context, firstId);
  }
}

interface MaintenanceRequestFixture {
  readonly propertyId: string;
  readonly partyId: string;
  readonly categoryId: string;
}

function resolveMaintenanceRequestFixture(context: NgbScenarioContext): MaintenanceRequestFixture | null {
  const propertyId = resolveFixtureId('NGB_PM_FIXTURE_PROPERTY_ID')
    ?? firstItemId(context.catalogs.listCatalogItems(PM_CATALOG_TYPES.property, { offset: 0, limit: 1 }));
  const partyId = resolveFixtureId('NGB_PM_FIXTURE_PARTY_ID', 'NGB_PM_FIXTURE_TENANT_PARTY_ID')
    ?? firstItemId(context.catalogs.listCatalogItems(PM_CATALOG_TYPES.party, { offset: 0, limit: 1 }));
  const categoryId = resolveFixtureId('NGB_PM_FIXTURE_MAINTENANCE_CATEGORY_ID')
    ?? firstItemId(context.catalogs.listCatalogItems(PM_CATALOG_TYPES.maintenanceCategory, { offset: 0, limit: 1 }));

  if (!propertyId || !partyId || !categoryId) {
    return null;
  }

  return { propertyId, partyId, categoryId };
}

function maintenanceRequestPayload(
  fixture: MaintenanceRequestFixture,
  subject: string,
  priority: 'normal' | 'high',
  requestedAtUtc: string,
): Record<string, unknown> {
  return {
    fields: {
      property_id: fixture.propertyId,
      party_id: fixture.partyId,
      category_id: fixture.categoryId,
      priority,
      subject,
      description: 'Generated by NGB platform performance tests.',
      requested_at_utc: requestedAtUtc,
    },
  };
}
