#!/bin/sh
set -eu

: "${VITE_API_BASE_URL:=}"
: "${VITE_BACKGROUND_JOB_URL:=}"
: "${VITE_KEYCLOAK_CLIENT_ID:=}"
: "${VITE_KEYCLOAK_ON_LOAD:=}"
: "${VITE_KEYCLOAK_POST_LOGOUT_REDIRECT_URL:=}"
: "${VITE_KEYCLOAK_REALM:=}"
: "${VITE_KEYCLOAK_REDIRECT_URL:=}"
: "${VITE_KEYCLOAK_ROLE_ADMIN:=}"
: "${VITE_KEYCLOAK_SILENT_CHECK_SSO_ENABLED:=}"
: "${VITE_KEYCLOAK_SILENT_CHECK_SSO_REDIRECT_URI:=}"
: "${VITE_KEYCLOAK_URL:=}"
: "${VITE_WATCHDOG_URL:=}"

envsubst '${VITE_API_BASE_URL} ${VITE_BACKGROUND_JOB_URL} ${VITE_KEYCLOAK_CLIENT_ID} ${VITE_KEYCLOAK_ON_LOAD} ${VITE_KEYCLOAK_POST_LOGOUT_REDIRECT_URL} ${VITE_KEYCLOAK_REALM} ${VITE_KEYCLOAK_REDIRECT_URL} ${VITE_KEYCLOAK_ROLE_ADMIN} ${VITE_KEYCLOAK_SILENT_CHECK_SSO_ENABLED} ${VITE_KEYCLOAK_SILENT_CHECK_SSO_REDIRECT_URI} ${VITE_KEYCLOAK_URL} ${VITE_WATCHDOG_URL}' \
  < /etc/nginx/templates/runtime-config.js.template \
  > /usr/share/nginx/html/runtime-config.js

exec nginx -g 'daemon off;'

