<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NGB.Platform.Api" Version="[$(NgbPlatformVersion)]" />
        <PackageReference Include="NGB.Platform.Application.Abstractions" Version="[$(NgbPlatformVersion)]" />
        <PackageReference Include="NGB.Platform.Contracts" Version="[$(NgbPlatformVersion)]" />
        <PackageReference Include="NGB.Platform.Core" Version="[$(NgbPlatformVersion)]" />
        <PackageReference Include="NGB.Platform.Hosting.AspNetCore" Version="[$(NgbPlatformVersion)]" />
        <PackageReference Include="NGB.Platform.PostgreSql" Version="[$(NgbPlatformVersion)]" />
        <PackageReference Include="NGB.Platform.PostgreSql.AspNetCore" Version="[$(NgbPlatformVersion)]" />
        <PackageReference Include="NGB.Platform.Runtime" Version="[$(NgbPlatformVersion)]" />
        <PackageReference Include="NGB.Platform.Runtime.Hosting" Version="[$(NgbPlatformVersion)]" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="../Shared/ApplicationRoles.cs" Link="ApplicationRoles.cs" />
    </ItemGroup>

</Project>
