export const AGENCY_BILLING_WEB_DEV_HOST = 'localhost'
export const AGENCY_BILLING_WEB_DEV_PORT = 5175
export const AGENCY_BILLING_WEB_DEV_BASE_URL = `http://${AGENCY_BILLING_WEB_DEV_HOST}:${AGENCY_BILLING_WEB_DEV_PORT}`
