name: publish-platform-nuget
run-name: Publish NGB ${{ github.sha }}

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  publish-certified-release:
    uses: ./.github/workflows/publish-platform-release.yml
    secrets: inherit
